### ISSUE TITLE
Missing LPF when monitoring current in voltage mode

### ISSUE THREAD

**Issue by steph643** [simplefoc/Arduino-FOC#102]
All SimpleFOC data are monitored after being filtered. This allows users to tune the LPF settings. One exception though: in voltage mode, "current" values are sent to Serial without filtering. This is annoying when tuning with SimpleFOCStudio.

**Comment by steph643** [comment]
Possible fix in FOCMotor.cpp line 107:
```C
    if(current_sense){
      if(torque_controller == TorqueControlType::foc_current) 
         c = current;
      else {
    	  c = current_sense->getFOCCurrents(electrical_angle);
          c.q = LPF_current_q(c.q);
          c.d = LPF_current_d(c.d);
      }
    }
```

**Comment by askuric** [comment]
You're right, thanks for the suggestion!  
We need some cleaning up there, around what is shown in what mode in the monitor.
We will integrate, at least this fix, in the next release
