### ISSUE TITLE
Where is equation 3

### ISSUE THREAD

**Issue by MapleHan** [simplefoc/Arduino-FOC#104]
https://github.com/simplefoc/Arduino-FOC/blob/a4f99990d7a120a2b0d3dfaaca9576b4f0d5656b/src/sensors/Encoder.cpp#L123

**Comment by askuric** [comment]
Ah, I thought I've answered this one already :smile: 

I guess you want to ask where does this code come from and what equation am I referring to as eq 3. :D
I remeber having the link of the paper in the comments but I guess it has disappeared at some point.

The velocity calculation algorithm is called the Mixed Time-Frequency Method and has been introduced by the paper: 

*"An embedded system for position and speed measurement adopting incremental encoders." by Petrella, Roberto, and Marco Tursini. IEEE Transactions on industry applications 44.5 (2008): 1436-1444.*

It is a very nice and simple algorithm that combines the velocity calculation as:
- measurement of the number of pulses that are counted in some fixed period of time  (precise on high velocities)
- measurement of the time in between two pulses (precise on low velocities)

Which improves the precision on both high and low velocities.

And the whole velocity calculation algorithm is implemented following the paper I've mentioned above and the equation numbers in the comments will correspond with the paper equation numbers.

I've also made a simple bare minimal Arduino example of this code in the repo: https://github.com/askuric/Arduino-Encoder-Mixed-Time-Frequency-Method
