### ISSUE TITLE
Can you give explanation of DRV8302 - High performance BLDC driver using Nucleo-64 F401RE example?

### ISSUE THREAD

**Issue by nonlinear1** [simplefoc/Arduino-FOC#107]
I am trying the DRV8302 - High performance BLDC driver using Nucleo-64 F401RE example, But I found no explanation about this example. Could someone knnow how to let Nucleo-64 F401RE run this example?
Think you very much!

**Comment by askuric** [comment]
Hey @nonlinear1,

The code is exactly the same, and the connection diagram as well, as in https://docs.simplefoc.com/drv8302_example 
You are right that I should have precised it more in the docs though :smile:

**Comment by nonlinear1** [comment]
You means the same? I think the F401RE the pin number or pin name is different from Arduino UNO! for pin configuration:#define   INH_A 9
#define   INH_B 10
#define   INH_C 11
#define   EN_GATE 8
#define   M_PWM 6 
#define   M_OC 5
#define   OC_ADJ 7
is the same? 
Here is the picture of stm32 version
![1](https://user-images.githubusercontent.com/19766939/129683655-520a25ae-6933-4ca4-b160-1feb98c37b73.jpg)
![2](https://user-images.githubusercontent.com/19766939/129683669-c3ff47b6-9519-4f1f-873f-10fe8b709b28.jpg)

**Comment by askuric** [comment]
Yes, I guess you are right.
In the video I might have used different pins but it was mostly due to the convenience (to avoid the wire entaglement :smile: ) .
You can use exactly the same pins as for the Arduino UNO with your Nucleo-64 Board.

The only issue that I had sometimes was using the pwm on the pin `11`, so I'd suggest you to use the pin `13` instead pinout like this:
```
#define   INH_A 9
#define   INH_B 10
#define   INH_C 13
#define   EN_GATE 8
#define   M_PWM 6 
#define   M_OC 5
#define   OC_ADJ 7
```

**Comment by nonlinear1** [comment]
Thank you Askuric! You are a kind-hearted and give me great help :)

**Comment by nonlinear1** [comment]
I am a newer for Arduino. I want to know your pin name definition.
for the specification of  Nucleo-64 F401RE is as follow: 
![Screenshot from 2021-08-17 16-27-02](https://user-images.githubusercontent.com/19766939/129691916-81a0ba86-06ac-48cb-bf3c-498ef5f0d312.png)
your definition of pin, for exampe: pin 11 means D11 as in the specification of Nucleo-64 F401RE?

**Comment by askuric** [comment]
Yes that is exactly it, sometimes the piout diagrams get useful as well. You can find the by googling relativey easity: 
Here is one of the nucleo-64 F401RE

![image](https://user-images.githubusercontent.com/36178713/129693951-c76db8bd-99b3-4d91-b0cb-83876ec99593.png)

**Comment by nonlinear1** [comment]
Thank you very much!

**Comment by nonlinear1** [comment]
@askuric Can I run the example of DRV8302 without the Encoder?

**Comment by askuric** [comment]
Hey @nonlinear1,
I'm going to close this issue. If you have some more questions feel free to reopen it or create a new one. 
There is also the community.simplefoc.com which is very active and can give you some more responsive solutions 😄
