### ISSUE TITLE
STM32 cannot drive the 6PWM code of DRV8302

### ISSUE THREAD

**Issue by PercentagePoint** [simplefoc/Arduino-FOC#119]
I try the example code, the 3PWM code Run in the STM32,  STM32 IO can output PWM signal, but Run 6PWM code ,the STM32 it seems not any signal output, Is this a bug?

the following is test code, I user the TIMER1 channel 1,channel 2,channel 3 of STM32F103RET6.

BLDCDriver6PWM driver = BLDCDriver6PWM(PA8, PA9, PA10, PB13, PB14, PB15, PC9);//no signal output
//BLDCDriver3PWM driver = BLDCDriver3PWM(PA8, PA9, PA10, PC9);//have signal output
![屏幕截图 2021-10-13 162435](https://user-images.githubusercontent.com/92427076/137096299-4c12a14d-ecc0-48b8-9d74-980a0c94bfde.jpg)
![屏幕截图 2021-10-13 162544](https://user-images.githubusercontent.com/92427076/137096309-d51b1fb4-8414-4748-a663-34771967b543.jpg)

**Comment by askuric** [comment]
Hey @PercentagePoint,
Thanks for the heads up, I'll test it today. It is possible that there are some conflicts with the new library code. 
Can you please test if you have the same issue with the v2.1.1?

**Comment by askuric** [comment]
Hey @PercentagePoint,

A quick update, I am still not sure why are you having issues really. 
I've tested the code with the stm32f103c8t6 (bluepill) and stm32f466re (nucleo-64) and they generate the 6pwm with both new and older releases. 
Which verison of the stm32duino are you using?

**Comment by PercentagePoint** [comment]
Hey @askuric 

You are right, maybe is my own problem, because I tested the code on my stm32f103c8t6 broad, but there is still a problem,  I also think it is the STM32duino version problem, this is the download addressof the STM32duino version I used,
https://github.com/rogerclarkmelbourne/Arduino_STM32
 where are you downloaded the code, can you share the download address?

**Comment by PercentagePoint** [comment]
I layout a STM32F103C8T6 board, which is used to drive two L6324 to two brushless motors. The code can run normally, but when the current loop control is added, the motor vibrates strongly. This is a new problem, and I have no clue about this problem.

**Comment by PercentagePoint** [comment]
![2](https://user-images.githubusercontent.com/92427076/140274214-41ba2696-f4bb-4067-b548-152fcfdc334e.png)
![1](https://user-images.githubusercontent.com/92427076/140274224-8df370f5-af0d-46b4-b05a-b4940dbd660c.png)

**Comment by askuric** [comment]
We do not support the roger clark's version of the stm32 support dirrectly. 
Please do install the official stm32 package stm32duino: https://github.com/stm32duino/Arduino_Core_STM32
