### ISSUE TITLE
Will esp32-s2 be supported

### ISSUE THREAD

**Issue by kluoyun** [simplefoc/Arduino-FOC#120]
Alternatives for soc/mcpwm_reg.h: []
ResolveLibrary(soc/mcpwm_reg.h)C:\Users\23398\Documents\Arduino\libraries\Simple_FOC\src\drivers\hardware_specific\esp32_mcu.cpp:6:10: fatal error: soc/mcpwm_reg.h: No such file or directory

  -> candidates: [] #include "soc/mcpwm_reg.h"

          ^~~~~~~~~~~~~~~~~
compilation terminated.

Changing the board to esp32 can compile normally, and esp32s2 fails

**Comment by runger1101001** [comment]
Compared to the previous ESP32 chips, the ESP32-S2 does not have the MPWM (motor PWM) peripheral.

It has the LED_PWM, so in theory we could probably support a basic 3-PWM mode, but it would be difficult to support all the features in the way the previous chip does.

Currently, I assume the ESP32 hardware specific code does not account for these chip generation differences. Certainly we should make it compile cleanly (and at least support generic PWM).

**Comment by askuric** [comment]
ESP32 s2 and c3 which do not have mcpwm are now supported from the v2.2.1
