### ISSUE TITLE
soc_caps.h missing error after compilation

### ISSUE THREAD

**Issue by Naman-C-Durve** [simplefoc/Arduino-FOC#167]
When SimpleFOC library is downloaded soc_caps.h file is missing from the Simple_FOC/src/drivers/hardware_specific. Error comes up after compilation.

**Comment by runger1101001** [comment]
soc_caps.h isn't part of SimpleFOC. IIRC it has something to do with ESP32 framework?

Which MCU are you using, and what compiler error do you see? We'll need a bit more information if we're to help you...

**Comment by askuric** [comment]
#162
