### ISSUE TITLE
I want to ask, is this a complete project？

### ISSUE THREAD

**Issue by zouzhe1** [simplefoc/Arduino-FOC#178]
Why didn't I find out how to control the motor, such as PWM input, CAN and UAVCAN and UART control？

**Comment by runger1101001** [comment]
Dear zouzhe1,

Whether we are "complete" depends on the needs of the person asking this question...

We provide a library to do field oriented control of brushless motors and steppers on Arduino. Around this project there is large amount of supporting code, including drivers for sensors and encoders of different types, and drivers for comms.

For UART, we offer the "Commander" interface for control, and the "Monitoring" interface for telemetry. They are part of the core library.

In our drivers library, we have an I2CCommander, for I2C based control.

We also have a StepDirListener for step/direction control, and various examples for control by CAN, OSC and others can be found in our examples, and by searching our forum.

How you put these things together is up to you - we provide only a library, the "building blocks", but not a finished application or ESC firmware. These are things you can build using our software as a base if you so choose.

We hope you find the library useful, and are open to suggestions for improvements!
