### ISSUE TITLE
if (dt < 0.0f ) dt = 1e-3f;  when dt  = 0 or   0 < dt <1e-3

### ISSUE THREAD

**Issue by FFiot** [simplefoc/Arduino-FOC#180]
Arduino-FOC\src\common\lowpass_filter.cpp
LowPassFilter::operator() 
Line 16
if (dt < 0.0f ) dt = 1e-3f;  
Change to 
if (dt <= 0.0f ) dt = 1e-3f;     or     if (dt < 1e-3f;) dt = 1e-3f;

**Comment by askuric** [comment]
Sorry for the delay, but I have rushed to the decision a bit to early with my earlier message. 
The change `if (dt <= 0.0f ) dt = 1e-3f;` is unnecessary becasue the case when `dt=0` is already well handled in the code.
