### ISSUE TITLE
Problem about developing STM32 in Platformio

### ISSUE THREAD

**Issue by ZhangYanglyu** [simplefoc/Arduino-FOC#187]
**Describe the bug**
.pio\libdeps\genericSTM32F103ZE\Simple FOC\src\current_sense\hardware_specific\stm32\stm32f1\stm32f1_hal.cpp: In function 'uint32_t _timerToRegularTRGO(HardwareTimer*)':
.pio\libdeps\genericSTM32F103ZE\Simple FOC\src\current_sense\hardware_specific\stm32\stm32f1\stm32f1_hal.cpp:36:12: error: 'ADC_EXTERNALTRIGINJECCONV_T8_TRGO' was not declared in this scope; did you mean 'ADC_EXTERNALTRIGINJECCONV_T1_TRGO'?
   36 |     return ADC_EXTERNALTRIGINJECCONV_T8_TRGO;
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |            ADC_EXTERNALTRIGINJECCONV_T1_TRGO
*** [.pio\build\genericSTM32F103ZE\libcf4\Simple FOC\current_sense\hardware_specific\stm32\stm32f1\stm32f1_hal.cpp.o] Error 1

**IDE you are using**
- Platformio
- Win10

**SimpleFoc version**
- SimpleFoc2.2.2+sha.817f45

Please help me to solve this problem.

**Comment by askuric** [comment]
Hey @ZhangYanglyu,
It is a typo in the code, thanks for reporting it. The dev branch will have it resolved from now on.

If you wanna relove it in your code, in your `stm32f1_hal.cpp` file on the line 36 put :
```
return ADC_EXTERNALTRIGCONV_T8_TRGO;
```

**Comment by ZhangYanglyu** [comment]
Thanks!
