### ISSUE TITLE
[BUG] samd21_mcu.cpp file ignored, builds using generic_mcu.cpp instead. Renaming to stsamd21_mcu works.

### ISSUE THREAD

**Issue by arturohernandez10** [simplefoc/Arduino-FOC#189]
**Describe the bug**
I am using a qtpy_mo adafruit board. While building the binary _samd21_mcu.cpp_  is used instead of _generic.mcu.cpp_.

**Details**
I soldered the swd pins and got my debugger working. As I step through the code when it calls `_writeDutyCycle4PWM`. The debugger steps into the _generic_mcu.cpp_ version. I spent a good amount of time looking at how the compiler decides to use the different files in the `hardware_specific` folder. I suspect it's there is a file naming convention. And the Arduino documentation I found, was vague but seemed to say the same. I ended up looking at the klipper repo and saw the path has the `atsamd` name. I changed the all the files to prefix them with **st** locally (e.g. _stsamd21_mcu.cpp_ ) and now I can step through `writeSAMDDutyCycle`. And my stepper is finally rotating as well!!!

I am happy to do any testing on this issue.

**IDE you are using**
- Platformio

**Comment by runger1101001** [comment]
Do you have the option
`lib_archive = false`
In your platformio.ini ?

**Comment by arturohernandez10** [comment]
I will try it.  Thanks!

**Comment by askuric** [comment]
hey @arturohernandez10, 
did you have time to test this?

**Comment by ShangHTao** [comment]
Disappeared？

**Comment by askuric** [comment]
I'm closing this issue, @arturohernandez10  if you still have it feel free to reopen it.
