### ISSUE TITLE
 MagneticSensorI2C.cpp file missing.

### ISSUE THREAD

**Issue by bgvsan** [simplefoc/Arduino-FOC#19]
Got the file missing from the minimal repo.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/4590043/92525166-a38e2380-f223-11ea-83f5-d2731324ef19.png">

**Comment by askuric** [comment]
Hey @bgvsan  
I've not updated the minimal branch with the new library version until today. 
https://github.com/simplefoc/Arduino-FOC/tree/minimal

This issue is now solved.
