### ISSUE TITLE
[BUG] ESP32 build error: unused variable - raw_adc

### ISSUE THREAD

**Issue by david-vankampen** [simplefoc/Arduino-FOC#208]
`current_sense/hardware_specific/esp32/esp32_mcu.cpp` line 71 defines `uint32_t raw_adc;` local to the method but it is never referenced, resulting in a build failure for an undefined variable.  Commenting that line allows the build to complete.

**Describe the hardware setup**
esp32 devkit v4

**IDE you are using**
- Arduino IDE

**Comment by askuric** [comment]
Thanks david,
This has been fixed in the dev and will enter into the next release soon.
