### ISSUE TITLE
[FEATURE]open loop exemples dont show reverse motion 

### ISSUE THREAD

**Issue by tripod2** [simplefoc/Arduino-FOC#254]
its a bit strange that i dont found any way to rotate a bldc in both direction especially for those gimbal motor

**Comment by askuric** [comment]
Hey @tripod2,
The motors can be reversed by sending a negative voltage/velocity/position target command. Can you tell us a bit more about your setup and what have your tried so far, so we can give you some more hints about this issue.

**Comment by runger1101001** [comment]
I have added some comments in the examples.
