### ISSUE TITLE
A confusion about the FOC algorithm

### ISSUE THREAD

**Issue by techHappyWater** [simplefoc/Arduino-FOC#278]
Hello, I have a question, when using the sine mode to drive the BLDC motor, by changing the duty cycle of different phase PWM to equivalent a phase voltage to the voltage we need, but when all phase PWM levels are low at the same time, all low side MOS are on at the same time, the motor three-phase is equivalent to short circuit, which will not cause the motor to slow down?

**Comment by runger1101001** [comment]
If it is ok with you, I will now close this question issue - if you have more questions, please feel free to open more issues, or even better, post them to our community at https://community.simplefoc.com
