### ISSUE TITLE
Works perfectly for around 2 minutes. Then it spins randomly.

### ISSUE THREAD

**Issue by AmExptl** [simplefoc/Arduino-FOC#287]
Works perfectly open loop (velocity) both separately and together (both motor control and sensor readings).  But, in closed loop (velocity) it only works perfectly for about 2 and half minutes. Then it spins randomly. This happens every single time. Starts perfectly after reset.  Using the example code for Closed Loop Velocity.  Used ...MagneticSensorSPI sensor = MagneticSensorSPI(10, 14, 0x3FFF);  What am I doing wrong ???

**Describe the hardware setup**
- SimpleFoc mini
- Gimbal motor 13.7 ohm 11 pole pairs
- Arduino Uno 
- AS5048A (SPI) magnetic sensor.
- Current sensing used? No
- Arduino IDE 

**Tried the Getting started guide? - if applicable**
Completed

**Comment by runger1101001** [comment]
Hey, this has been traced to a bug in the velocity function, which has been fixed on the dev branch, and will be part of the next release.
