### ISSUE TITLE
About MCPWM?

### ISSUE THREAD

**Issue by zhuangfengzi** [simplefoc/Arduino-FOC#30]
What are these mistakes? How to solve this problem? thank you!

e:\Program Files (x86)\Arduino\libraries\Arduino-FOC-v.1.5.0\src\FOCutils.cpp:108:55: error: 'MCPWM_SELECT_SYNC_INT0' was not declared in this scope

   mcpwm_sync_enable(m_slot.mcpwm_unit, MCPWM_TIMER_0, MCPWM_SELECT_SYNC_INT0, 0);

                                                       ^

exit status 1
Error compiling for development board esp32 dev module

**Comment by askuric** [comment]
You have the explanation in ESP32 docs:
https://docs.simplefoc.com/microcontrollers

You will have to replace the mcpwm.h file.

**Comment by zhuangfengzi** [comment]
@askuric 
Focsimple is great! Thank you very much.

**Comment by askuric** [comment]
I'm happy you like it and that you've found your solution! 
https://github.com/simplefoc/Arduino-FOC/issues/14
