### ISSUE TITLE
PID not using the latest error for proportional term

### ISSUE THREAD

**Issue by owennewo** [simplefoc/Arduino-FOC#31]
The PID calcs have:
```
float PIDController::operator() (float error){
    .....
    float proportional = P * error_prev;
```
Shouldn't that be `float proportional = P * error;` ?
It's only adding a tiny bit of latency so not a serious problem but was wondering if I'm overlooking something

**Comment by askuric** [comment]
Absolutely right, I'll fix this right away!

**Comment by askuric** [comment]
Integrated into [v2.0](https://github.com/simplefoc/Arduino-FOC/releases/tag/v2.0)
