### ISSUE TITLE
Why does the motor turn left and right twice at the beginning when I call the closed loop program?

### ISSUE THREAD

**Issue by CJT1111** [simplefoc/Arduino-FOC#310]
Hello, why is it that when I call a closed-loop program, the motor rotates two times from side to side at the beginning? Is it calibration? Can you cancel it?

**Comment by runger1101001** [comment]
This is the calibration required to find the electrical zero point.

After you have run it once, you can re-use the values found by remembering them and passing them to motor.initFOC(). Please see our documentation for further details.

**Comment by CJT1111** [comment]
Thank you for your reply and I wish you all the best.
