### ISSUE TITLE
[BUG] incorrect pins used in DRV8302 6-PWM example

### ISSUE THREAD

**Issue by Abi-64** [simplefoc/Arduino-FOC#345]
in this example:
examples/hardware_specific_examples/DRV8302_driver/6pwm_example/encoder/full_control_serial/full_control_serial.ino
Line 32:
BLDCDriver6PWM driver = BLDCDriver6PWM(INH_A,INH_A, INH_B,INH_B, INH_C,INL_C, EN_GATE);

Should be:
BLDCDriver6PWM driver = BLDCDriver6PWM(INH_A,INL_A, INH_B,INL_B, INH_C,INL_C, EN_GATE);

Right?

**Comment by runger1101001** [comment]
Yes, it most definately should. Thanks for spotting it! I will fix it right away.

**Comment by runger1101001** [comment]
Fixed in https://github.com/simplefoc/Arduino-FOC/pull/350
