### ISSUE TITLE
[FEATURE] Add library.json to set libArchive? 

### ISSUE THREAD

**Issue by timohueser** [simplefoc/Arduino-FOC#357]
Hi,

When using simpleFOC with PlatformIO one currently has to set `lib_archive = false` in the platformio.ini file. This is a little bug-prone, as forgetting that line leads to some hard to troubleshoot failure modes (On my RP2040 it made it impossible to change the PWM frequency, with everything else working as expected).

In my opinion a less bug-prone way of dealing with this would be to add the following **library.json** file in the root of the project: 

    {
      "build": {
        "libArchive": false
      }
    }

As far as I can tell this has the same effect and can't be forgotten by the user :)

**Comment by runger1101001** [comment]
Wow, thank you for this hint! Is this a platformIO specific file or will this then also affect ArduinoIDE?

**Comment by runger1101001** [comment]
Thanks for this, it looks like a PlatformIO specific file, so this looks kind of perfect for us. I will add it in the next release.
