### ISSUE TITLE
[FEATURE] Allowing to choose SPI pins

### ISSUE THREAD

**Issue by sylque** [simplefoc/Arduino-FOC#375]
**Is your feature request related to a problem? Please describe.**
On my ESP32, I can choose any GPIO pins for SPI. Unfortunately, it seems SimpleFOC only allows for the two sets of default SPI pins (HSPI and VSPI), like this:
```c++
static SPIClass spi(HSPI);
sensor.init(&spi);
```

**Describe the solution you'd like**
```c++
sensor.init(int8_t sck=-1, int8_t miso=-1, int8_t mosi=-1, int8_t ss=-1);
```

**Comment by runger1101001** [comment]
This bug is being handled here: https://github.com/simplefoc/Arduino-FOC-drivers/issues/37

So I will close this issue now.
