### ISSUE TITLE
[BUG] Monitor downsampling cannot be disabled

### ISSUE THREAD

**Issue by sylque** [simplefoc/Arduino-FOC#377]
**Describe the bug**
There seems to be no way to disable monitor downsampling. Setting `monitor_downsample` to zero disables monitoring altogether.

The reason lies [here](https://github.com/simplefoc/Arduino-FOC/blob/master/src/common/base_classes/FOCMotor.cpp#L94):
```c++
if( !monitor_downsample || monitor_cnt++ < monitor_downsample ) return;
```
This should be replaced by:
```c++
if(monitor_cnt++ < monitor_downsample ) return;
```

**Describe the hardware setup**
ESP32 + SimpleFOCMini + AS4048A + miniatute gimbal motor

**IDE you are using**
Platformio

**Comment by askuric** [comment]
This would be a breaking change as down-sampling of 0 is intentionally intended to seamlessly disable monitoring. So many users have used this way in the past. (including me :D) 
So what I propose is to do this :
```cpp
  if( !monitor_downsample || monitor_cnt++ < (monitor_downsample-1) ) return;
```
Now down-sample of 1 actually disables down-sampling.

**Comment by sylque** [comment]
Looks great, thanks.
