### ISSUE TITLE
[BUG] Error in doc: initFOC() cannot be used in open loop mode

### ISSUE THREAD

**Issue by sylque** [simplefoc/Arduino-FOC#382]
On page https://docs.simplefoc.com/velocity_openloop, in the sample code, there is this line:
```c++
motor.initFOC();
```
I think it shouldn't be here, as initFOC() is not compatible with open loop mode.

**Comment by askuric** [comment]
hmm, I mean you can use the initFOC with the openloop, the only problem is that it will disable the motor. So if you call the inifFOC you need to enable the motor afterwards. :D
I agree that is not the best practice.

So, from now on, the `initFOC` can be used will allow the initialisation of the openloop if no sensor is available. It will not disable the motor.
