### ISSUE TITLE
Is this FOC suppot high speed BLDC(5000rpm)?[FEATURE]

### ISSUE THREAD

**Issue by jnxyatmjx** [simplefoc/Arduino-FOC#391]
**Is your feature request related to a problem? Please describe.**
Description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
I just have a quest , Dose  this FOC support drive high speed BLDC?

**Describe alternatives you've considered**
Description of any alternative solutions or features you've considered.

**Additional context**

**Comment by runger1101001** [comment]
Dear @jnxyatmjx ,

Our users have run motors in excess of 40000RPM, so achieving 5000RPM is possible.

It depends on the correct choice of hardware including sensor, driver and MCU. In particular, you're unlikely to achieve such high speeds on a slow MCU like the Arduino UNO, you'll have to pick something faster.

If its ok, I will close this issue now.

**Comment by jnxyatmjx** [comment]
> Dear @jnxyatmjx ,
> 
> Our users have run motors in excess of 40000RPM, so achieving 5000RPM is possible.
> 
> It depends on the correct choice of hardware including sensor, driver and MCU. In particular, you're unlikely to achieve such high speeds on a slow MCU like the Arduino UNO, you'll have to pick something faster.
> 
> If its ok, I will close this issue now.

clear , thank you
