### ISSUE TITLE
Raspberry Pi Pico support

### ISSUE THREAD

**Issue by kimiolek** [simplefoc/Arduino-FOC#80]
There is any plans to add support for Raspberry Pi Pico?

**Comment by runger1101001** [comment]
The support has been introduced in the recent 2.1.1 release of SimpleFOC. 

It is so new, I think it is not yet in the documentation. :-)
MagneticSensorSPI is unfortunately currently not supported, and there is not yet any current sensing.

But you can run motors in 3-PWM and 6-PWM configurations.
