### ISSUE TITLE
Fail to compile for ESP32 error: '_ADC_VOLTAGE' was not declared in this scope

### ISSUE THREAD

**Issue by bgvsan** [simplefoc/Arduino-FOC#89]
from the latest changes:
![image](https://user-images.githubusercontent.com/4590043/120398479-a2b19a80-c33a-11eb-973b-51c53daa5643.png)

**Comment by bgvsan** [comment]
looks few esp32 test are excluded, maybe to address that issue we need to set a test for each platform supported.

**Comment by askuric** [comment]
This is the dev branch?

**Comment by bgvsan** [comment]
> This is the dev branch?

Yes

**Comment by askuric** [comment]
Yeah, i think that the dev branch is properly broken at this moment. We'll change this soon though. 

You're right that this would be good to make. The only problem is the pinout and we would need to specify which examples to compile for which architecture. It's a bit of pain to make but i suppose it is possible and it makes sense for sure.

**Comment by bgvsan** [comment]
> Yeah, i think that the dev branch is properly broken at this moment. We'll change this soon though. 
> 
> 
> 
> You're right that this would be good to make. The only problem is the pinout and we would need to specify which examples to compile for which architecture. It's a bit of pain to make but i suppose it is possible and it makes sense for sure.:D

I would have fixed if I know were we want to go but I we not been following any discussion recently. 
I can understand is a pain. I ve look at it and i still don't understood how. I need to learn a lot on this side.

No problem, will be a good to do for the future

**Comment by askuric** [comment]
Ok, this has been fixed int the dev some time ago. And we've updated the github runners to compile for almost all  the target architectures so these things should not happen any more :)
