### ISSUE TITLE
Unintended double promotions.

### ISSUE THREAD

**Issue by sDessens** [simplefoc/Arduino-FOC#98]
On platforms that have compiler support for doubles, such as the stm32, there are a lot of unintended float-to-double conversions in the code. I was able to reduce move() duration from 14us to 6us by eliminating just one of these unintended casts, and loopFOC() from 144us to 50us by replacing several. Almost all files have unintended promotions in them.

These instances can be easily found with -Wdouble-promotion and -Werror=double-promotion, there are a few hundred of them.

**Comment by runger1101001** [comment]
There is a patch applied to the dev branch which fixes many of them, I believe.

We should keep this issue open and do another round on this topic, to make sure we have caught them all.

**Comment by runger1101001** [comment]
Thank you for reporting this!

**Comment by sDessens** [comment]
The dev branch fixes a few unintended casts, but there are still many left. Such as:

````
#define _round(x) ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))
````
And:
````
#define _PWM_RANGE 4095.0// 2^12 -1 = 4095
_setPwm(pinA, _PWM_RANGE*dc_a, _PWM_RESOLUTION);
````
And:
````
duty_cycle1B = _constrain(abs(Ualpha)/voltage_power_supply,0.0,1.0);
````

I will report back later with a patch.

**Comment by sDessens** [comment]
See pull request #100

**Comment by sDessens** [comment]
Pull request merged
